### ISSUE TITLE
Unable to use this package

### ISSUE THREAD

**Issue by kbhagchandani** [temich666/t-json-viewer#1]
HI all I am not able to use this component in the project. as whenever I run this component it throws errors. I am able to trace that there is no index.js file available in the package.

Here i am sharing the browser console log:

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/t-json-viewer/index.js
	Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/t-json-viewer/index.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487330922173:889:29) [<root>]
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487330922173:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487330922173:345:33) [<root>]
	Error loading http://localhost:5555/node_modules/t-json-viewer/index.js as "t-json-viewer" from http://localhost:5555/app/dashboard/locations/locations.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487330922173:889:29) [<root>]
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487330922173:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487330922173:345:33) [<root>]
	Error loading http://localhost:5555/node_modules/t-json-viewer/index.js as "t-json-viewer" from http://localhost:5555/app/dashboard/locations/locations.module.js "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by sharkich** [comment]
Is this issue actual?

**Comment by kbhagchandani** [comment]
It is not working at my side. Let me know how can I help.

**Comment by sharkich** [comment]
I created index.js file. Could you check on your side?

**Comment by maninak** [comment]
Hey, there!
I think I am having the same or a similar problem in getting this module to run. Specifically I'm getting this error in the browser's console:

```
Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/home/maninak/Desktop/NoMoTS-webapp/node_modules/t-json-viewer/index.js'
```

I'm developing an Ionic web app using the latest Ionic v3.4.2 which uses angular v4.1.3. I have dumped node modules and reinstalled, and have checked multiple times that I'm not doing something horribly wrong.

Let me know if I can be of any further help in resolving this.

**Comment by sharkich** [comment]
I've developed v1.2.0. Could you test it?

**Comment by maninak** [comment]
Still getting a runtime error, although now it complains about the `index.js.map` missing, instead of `index.js`. I can manually verify that the former is missing and the latter is present in my node_modules.

Tested against same development setup as above with package.json dependency changed as `"t-json-viewer": "^1.2.0"`.

Full runtime error follows:
`Module build failed: Error: ENOENT: no such file or directory, open '/home/maninak/Desktop/NoMoTS-webapp/node_modules/t-json-viewer/index.js.map'`

**Comment by maninak** [comment]
You should probably have `"sourceMap": true` in your `tsconfig.json` file for your module and make `*.map` files are not gitignored.

Just a guess.

**Comment by sharkich** [comment]
It's strange. I've removed all configs from a package. All on your side.
Could you show your project or it's confidential?

**Comment by maninak** [comment]
Not at all, it's actually a new open source project of mine https://github.com/maninak/NoMoTS-webapp
