### ISSUE TITLE
This directive is not working properly in IE

### ISSUE THREAD

**Issue by kkapil24** [temich666/t-json-viewer#12]
Hi, When we try to open demo url **http://temich.in.ua/t-json-viewer/**  in IE, it doesn't work properly  and we see additional scroll bars (both horizontal and vertical) on each expansion.
Also, sometime performance is also slow. 

Please see the attached file:
![2017_05_26_14_59_04_t_json_viewer_example_angular_2_json_viewer_component](https://cloud.githubusercontent.com/assets/17264234/26489182/fa1211fc-4223-11e7-86fc-b2d0b3e7fd7d.jpg)

**Comment by jodevsa** [comment]
@temich666 to only show scroll bars when needed (overflow happen) we could do this:
`.t-json-viewer {
  font-family: monospace;
  font-size: 1em;
  width: 100%;
  overflow:auto;
  height:100%;
}`
What do you think?

**Comment by ramkurapati** [comment]
Hi,
I have added t-json-viewer dependency in my angular 2  CLI project.
When I try to build my project with command # ng build ,it's  giving below error
**ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in ../node_modules/t-json-viewer/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in ../node_modules/t-json-viewer/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in .../node_modules/t-json-viewer/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in .../node_modules/t-json-viewer/node_modules/@angular/core/index.d.ts, resolving symbol TJsonViewerModule in .../node_modules/t-json-viewer/src/t-json-viewer.module.ts, resolving symbol TJsonViewerModule in ..../node_modules/t-json-viewer/src/t-json-viewer.module.ts**

**Comment by sharkich** [comment]
I've developed v1.2.0. Could you test it?
