### ISSUE TITLE
 Unable to build my CLI project with t-json-viewer dependency

### ISSUE THREAD

**Issue by ramkurapati** [temich666/t-json-viewer#14]
Hi,
I have added t-json-viewer dependency in my angular 2 CLI project.
When I try to build my project with command # ng build ,it's giving below error
**ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in ../node_modules/t-json-viewer/node_modules//src/metadata/ng_module.d.ts, resolving symbol NgModule in ../node_modules/t-json-viewer/node_modules//src/metadata.d.ts, resolving symbol NgModule in .../node_modules/t-json-viewer/node_modules//src/core.d.ts, resolving symbol NgModule in .../node_modules/t-json-viewer/node_modules//index.d.ts, resolving symbol TJsonViewerModule in .../node_modules/t-json-viewer/src/t-json-viewer.module.ts, resolving symbol TJsonViewerModule in ..../node_modules/t-json-viewer/src/t-json-viewer.module.ts**

please help me on this.

**Comment by jodevsa** [comment]
provide more information ng version ?

**Comment by jodevsa** [comment]
same as #10  @temich666

**Comment by ramkurapati** [comment]
_                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.1
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.0-rc.1

**Comment by ramkurapati** [comment]
```

 @angular/cli: 1.0.0-rc.1
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.0-rc.1
```

**Comment by jodevsa** [comment]
try upgrading angular/cli to latest version ?

**Comment by kkapil24** [comment]
@jodevsa/ @ramkurapati  : I tried to use augmity/agm-json-viewer (https://github.com/augmity/agm-json-viewer) and it working fine with ng build. The only problem is performance but if we make the changes in **..\node_modules\agm-json-viewer\src\agm-json-viewer.component\agm-json-viewer.component.html** mentioned at https://github.com/temich666/t-json-viewer/pull/13/files/319396a4d91b08ac8245810db1cc12dfba70747c then it works fine.

**Comment by sharkich** [comment]
I've developed v1.2.0. Could you test it?
