### ISSUE TITLE
Can't import this module into a lazy loaded module

### ISSUE THREAD

**Issue by jbgarr** [temich666/t-json-viewer#15]
It seems that due to the fact that `t-json-viewer.module` pulls in the `BrowserModule` and that module is already pulled in in my AppModule there is a conflict. I'm trying to import this module into a lazy loaded module and get the following error:

`Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead`

**Comment by sharkich** [comment]
I've developed v1.2.0. Could you test it?
