### ISSUE TITLE
Please publish .d.ts files instead of .ts files on npmjs

### ISSUE THREAD

**Issue by ramaghanta** [temich666/t-json-viewer#16]
Hi,

Thank You for this great library. Would it be possible to publish .d.ts files instead of .ts files? Please refer to #https://github.com/Microsoft/TypeScript/issues/15363

Thanks!

**Comment by sharkich** [comment]
I've developed v1.2.0. Could you test it?

**Comment by ramaghanta** [comment]
Thanks for the quick turn around. While that definitely worked, it would have been a clean package had you exported just the .d.ts files in a something like a dist directory.
