### ISSUE TITLE
null value behaves as object

### ISSUE THREAD

**Issue by asleire** [temich666/t-json-viewer#20]
If the displayed JSON-object contains null-properties they will show as collapsible and generate an error when opened.

### Reproduce:
1. Display null property
`
let json = {
 value: null
}
`

2. Attempt to open property 
![image](https://user-images.githubusercontent.com/631907/28780309-83919c48-7606-11e7-9fbd-31ff2d89354a.png)

3. Error 
![image](https://user-images.githubusercontent.com/631907/28780330-9492189c-7606-11e7-91bc-fb28801f798b.png)

**Comment by jodevsa** [comment]
Confirmed, i'm working on a fix
@asleire @temich666

**Comment by jodevsa** [comment]
Done #21
