### ISSUE TITLE
On Collapse/Expand it duplicates the value 

### ISSUE THREAD

**Issue by kapiladiyecha** [temich666/t-json-viewer#22]
![image](https://user-images.githubusercontent.com/6995248/29760959-64e5d432-8be4-11e7-9e41-e15f84e192d5.png)

**Comment by jodevsa** [comment]
could you post the JSON  you are trying to view ? 
or any JSON that pop's this bug

**Comment by kapiladiyecha** [comment]
`{
	"Type": "Service",
	"NuGetConfig": {
	  "SolutionFilePath": "fn.sln",
	  "NugetProjectPath": null,
	  "AddDebugBuildJob": null,
	  "AddPreviewReleaseJob": null,
	  "UnitTestProjectPaths": null,
	  "Version": "1.4.3",
	  "NextBuildNumber": "343",
	  "RecipientList": null
	},
	"SFConfig": {
	  "SolutionFilePath": "fn.sln",
	  "SfProjectPath": "/test/",
	  "ClusterTypes": [
		"STANDARD",
		"AQL",
		"SFDC"
	  ],
	  "UnitTestProjectPaths": null,
	  "Version": "1.4.3",
	  "NextBuildNumber": "343",
	  "RecipientList": null
	},
	"JavascriptConfig": {
	  "RootDirectoryPath": null,
	  "ArtifactoryDirectoryName": null,
	  "BuildFolder": null,
	  "Product": null,
	  "IsGulpPackaging": null,
	  "NextBuildNumber": "343",
	  "RecipientList": null
	}
  }`

**Comment by sharkich** [comment]
Cannot reproduce this bug: https://github.com/temich666/t-json-viewer-example/commit/3f0021f12b2a1d38802f126a18bfa0cbe89cd235
