### ISSUE TITLE
"asset" defined private but used in HTML, throws error on ng build --prod

### ISSUE THREAD

**Issue by acrest** [temich666/t-json-viewer#6]
"asset" is define private in the .ts and throws an error when building with the --prod tag because the HTML needs it to be public. 

"asset" definition
`private asset: Array<Item> = [];`

And in the HTML "asset" is used in the *ngFor
```
<div
    *ngFor="let item of asset;"
    [ngClass]="['item__type--' + item.type, 'is-object-' + isObject(item), 'is-opened-' + item.isOpened]"
    class="item"
  >
```

Simple fix would be a public definition

**Comment by sharkich** [comment]
Tnx. Fixed.
