### ISSUE TITLE
Upgrade to Angular 4 Code

### ISSUE THREAD

**Issue by lidev42** [temich666/t-json-viewer#9]
Hey Temich666 thanks for the last update.  Here is something we have done to upgrade to angular 4 that you could possibly use.
![screen shot 2017-05-15 at 3 10 30 pm](https://cloud.githubusercontent.com/assets/18490505/26079655/c2fb8492-3980-11e7-9e91-0c86ce4fec70.png)

If that picture doesn't work, here is the code

`   "dependencies": {
 -    "@angular/core": "^2.3.1",
 +    "@angular/core": "^4.1.0",
      "@types/lodash": "^4.14.44",
      "lodash": "^4.17.3",
 -    "rxjs": "^5.0.1"
 +    "rxjs": "^5.1.1",
 +    "zone.js": "^0.8.10"
    },
    "devDependencies": {
 -    "tslint": "^4.0.2",
 -    "typescript": "~2.0.3"
 +    "tslint": "^5.2.0",
 +    "typescript": "~2.2.2"
    }
  }`

**Comment by sharkich** [comment]
Thanks for the comment. Done.
